### ISSUE TITLE
Demo workflow checking 

### ISSUE THREAD

**Issue by codkali** [Narcoguard/.github#7]
### Project Idea Title

Demo 

### Project Description

This is just a demo issue to check workflow

### Technology Stack

ymal

### Contribution Guidelines

#Demo

### Difficulty Level

Beginner

### Contact Email

codkali55@gmail.com

### GitHub Profile URL

https://github.com/codkali

### Other Contact Information (Optional)

_nil_

### Current Status

Student

**Comment by dhruvabhat24** [comment]
✅ Thank you for your project idea submission, @codkali!
Your idea will be reviewed, and if it aligns with our goals, we will proceed with the project.

**Comment by dhruvabhat24** [comment]
✅ Thank you for your membership request.
The organization admin (@dhruvabhat24) will look into your request soon.

**Comment by dhruvabhat24** [comment]
✅ Thank you for your project idea submission, @codkali!
Your idea will be reviewed, and if it aligns with our goals, we will proceed with the project.
